
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - /home/admlnx/mysql_data:/var/lib/mysql
    networks:
      - net-dimdim

  app-java:
    build:
     context: ../cp4-devops-docker-compose/cp2-java-2tds-main
     dockerfile: Dockerfile
    container_name: app-java
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql-db
        condition: service_healty
    networks:
      - net-dimdim

  dbgate:
    image: dbgate/dbgate
    container_name: dbgate
    ports:
      - "3000:3000"
    networks:
      - net-dimdim

networks:
  net-dimdim: